### ISSUE TITLE
Browser's name

### ISSUE THREAD

**Issue by talgautb** [roose/Wox.Plugin.CanIUse#3]
Why are you using another name for browser ? like in [alfred-caiuse](https://github.com/willfarrell/alfred-caniuse-workflow)
S -> Safari, not SF :)

**Comment by roose** [comment]
Based on alfred workflow does not mean full copy of that workflow :-) .
I use 2 letter abbreviation of browser names for better look.

**Comment by talgautb** [comment]
but if i use in work mac os with alfred and windows with wix, it will some problems :( i want to see similar letters
