### ISSUE TITLE
Does not seem to work with Wox

### ISSUE THREAD

**Issue by acicovic** [roose/Wox.Plugin.CanIUse#4]
Hi there,

Thank you for the work you've put in this plugin.

I am trying to run it in the last Wox pre-release (1.3.424). When I install it using wpm install caniuse it seems to install (it says installed and prompts for restart), but then I cannot see it in the plugin list and invoking the caniuse command does not seem to to anything.

Is there a plan to fix this?

Thanks!

**Comment by roose** [comment]
@acicovic Hello, sorry for the delayed response. You have installed python? Because this plugin need python for work.

**Comment by acicovic** [comment]
Hi,

Thank you for your comment! I installed python and now it works!

Perhaps you could mention this in the plugin's readme.md and also in the plugin's page so other can avoid the same problem.

Thanks again!

**Comment by roose** [comment]
Thank you @acicovic, I will definitely add this to the readme.
